# Taken from https://github.com/vadimkim/cert-manager-webhook-hetzner

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-issuer
  namespace: demaf
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: test@test.com
    privateKeySecretRef:
      name: letsencrypt-secret
    solvers:
      - dns01:
          webhook:
            groupName: acme.yourdomain.tld
            solverName: hetzner
            config:
              secretName: hetzner-secret
              apiUrl: https://dns.hetzner.com/v1
---
apiVersion: v1
kind: Secret
metadata:
  name: hetzner-secret
  namespace: cert-manager
type: Opaque
data:
  api-key: <base64-encoded-api-key>
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-ui-cert
  namespace: demnaf
spec:
  commonName: demaf.de
  dnsNames:
    - demaf.de
  issuerRef:
    name: letsencrypt-issuer
    kind: Issuer
  secretName: web-ui-tls