# Deployment and Service definitions for the models database

# modelsdatabase Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: modelsdatabase
  namespace: demaf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modelsdatabase
  template:
    metadata:
      labels:
        app: modelsdatabase
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - k8s-cluster3-7
      containers:
        - name: modelsdatabase
          image: mongo:5.0.6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: demaf-config
                  key: modelsdb_password
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: demaf-config
                  key: modelsdb_password
          livenessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 60
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 15
      hostname: modelsdatabase
      restartPolicy: Always
---
# modelsdatabase Service
apiVersion: v1
kind: Service
metadata:
  name: modelsdatabase
  namespace: demaf
spec:
  selector:
    app: modelsdatabase
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017