# Deployment and Service definitions for the RabbitMQ

# This uses the RabbitMQ Cluster Operator to manage RabbitMQ clusters in Kubernetes.
# See https://www.rabbitmq.com/kubernetes/operator/operator-overview for more details.
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: demaf
  labels:
    app.kubernetes.io/name: rabbitmq-cluster-operator
    app.kubernetes.io/version: v3.0.0
    app.kubernetes.io/component: rabbitmq-operator
    app.kubernetes.io/part-of: demaf
spec:
  replicas: 1
  persistence:
    storageClassName: vsphere-default
    storage: 10Gi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - k8s-cluster3-5
  