# This file contains the PersistentVolumeClaim definitions for the DeMAF application.

# PVC for the DeMAF application
# Used to store uploaded artifacts, final TADMs and all Helm templates that are used.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demaf-pvc
  namespace: demaf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vsphere-default
  resources:
    requests:
      storage: 100Mi
---
# PVC for the Winery
# Used to store initial configuration files of Winery and the generated configuration files by DeMAF
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: winery-pvc
  namespace: demaf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vsphere-default
  resources:
    requests:
      storage: 100Mi
---
# PVC is used for RabbitMQ
# Used to store RabbitMQ data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-data-pvc
  namespace: demaf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vsphere-default
  resources:
    requests:
      storage: 10Mi
---
# PVC is used for RabbitMQ
# Used to store RabbitMQ logs
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-logs-pvc
  namespace: demaf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vsphere-default
  resources:
    requests:
      storage: 5Mi
---
# PVC for the configurations database
# Used to store the configurations database data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: configurationsdb-pvc
  namespace: demaf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vsphere-default
  resources:
    requests:
      storage: 100Mi
---
# PVC for the tasks database
# Used to store the tasks database data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tasksdb-pvc
  namespace: demaf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vsphere-default
  resources:
    requests:
      storage: 100Mi
---
# PVC for the models database
# Used to store the models database data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: modelsdb-pvc
  namespace: demaf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vsphere-default
  resources:
    requests:
      storage: 1Gi