version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.9-management
    hostname: tad-rabbitmq
    container_name: tad-rabbitmq
    # volumes:
    #  - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
    #  - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    #  - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
    #  - ./rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672

  modelsdatabase:
    image: mongo:5.0.6
    hostname: modelsdatabase
    container_name: modelsdatabase
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: tad
      MONGO_INITDB_ROOT_PASSWORD: tad
    ports:
      - 27017:27017

  configurationsdatabase:
    image: postgres:14.2
    hostname: configurationsdatabase
    container_name: configurationsdatabase
    restart: always
    environment:
      POSTGRES_USER: tad
      POSTGRES_PASSWORD: tad
      POSTGRES_DB: configurations
    ports:
      - 5432:5432

  tasksdatabase:
    image: postgres:14.2
    hostname: tasksdatabase
    container_name: tasksdatabase
    restart: always
    environment:
      POSTGRES_USER: tad
      POSTGRES_PASSWORD: tad
      POSTGRES_DB: tasks
    ports:
      - 5433:5432
