version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.9-management
    hostname: tad-rabbitmq
    # volumes:
    #  - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
    #  - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    #  - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
    #  - ./rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672

  modelsdatabase:
    image: mongo:5.0.6
    hostname: modelsdatabase
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  configurationsdatabase:
    image: mongo:5.0.6
    hostname: configurationsdatabase
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27018:27017

  tasksdatabase:
    image: mongo:5.0.6
    hostname: tasksdatabase
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27019:27017